server:
  port: 8081
jwt:
  secret: fbaeb892-2b54-4c2e-b871-005611d70e62
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    #url: ${JDBC_DATABASE_URL}
    #username: ${JDBC_DATABASE_USERNAME}
    #password: ${JDBC_DATABASE_PASSWORD}
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
    continue-on-error: true

